<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-10URQEE" ignored="0" name="Add Customer Login Test" tests="4" failures="4" timestamp="21 Mar 2019 04:16:58 GMT" time="31.984" errors="0">
  <testcase name="addCustomer" time="7.728" classname="com.w2a.testcases.AddCustomerTest">
    <failure type="java.lang.AssertionError" message="Add Customer failed">
      <![CDATA[java.lang.AssertionError: Add Customer failed
at com.w2a.testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:52)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- addCustomer -->
  <testcase name="addCustomer" time="7.6" classname="com.w2a.testcases.AddCustomerTest">
    <failure type="java.lang.AssertionError" message="Add Customer failed">
      <![CDATA[java.lang.AssertionError: Add Customer failed
at com.w2a.testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:52)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- addCustomer -->
  <testcase name="addCustomer" time="7.621" classname="com.w2a.testcases.AddCustomerTest">
    <failure type="java.lang.AssertionError" message="Add Customer failed">
      <![CDATA[java.lang.AssertionError: Add Customer failed
at com.w2a.testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:52)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- addCustomer -->
  <testcase name="addCustomer" time="7.6" classname="com.w2a.testcases.AddCustomerTest">
    <failure type="java.lang.AssertionError" message="Add Customer failed">
      <![CDATA[java.lang.AssertionError: Add Customer failed
at com.w2a.testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:52)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- addCustomer -->
</testsuite> <!-- Add Customer Login Test -->
